# Generated by Django 5.0.2 on 2024-04-25 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('show_on_homepage', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='media')),
                ('description', models.TextField()),
                ('link1_title', models.CharField(blank=True, max_length=100)),
                ('link1_url', models.URLField(blank=True)),
                ('link2_title', models.CharField(blank=True, max_length=100)),
                ('link2_url', models.URLField(blank=True)),
                ('main_title1', models.CharField(max_length=200)),
                ('title1', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='media')),
                ('description1', models.TextField()),
                ('main_title2', models.CharField(max_length=200)),
                ('title2', models.CharField(max_length=200)),
                ('image2', models.ImageField(upload_to='media')),
                ('description2', models.TextField()),
            ],
        ),
    ]
