# Generated by Django 5.0.2 on 2024-04-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IndexPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_title', models.CharField(max_length=200)),
                ('index_image', models.ImageField(upload_to='media/img/')),
                ('index_description', models.TextField()),
                ('about_title', models.CharField(max_length=200)),
                ('about_image', models.ImageField(upload_to='media/img/')),
                ('about_description', models.TextField()),
                ('why_choose_us_title', models.CharField(max_length=200)),
                ('why_choose_us_description', models.TextField()),
                ('footer_instagram_link', models.URLField(blank=True, null=True)),
                ('footer_facebook_link', models.URLField(blank=True, null=True)),
                ('footer_phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('footer_email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
