# Generated by Django 5.0.2 on 2024-04-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpage',
            name='footer_X_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indexpage',
            name='footer_linkled_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
