# Generated by Django 5.0.2 on 2024-04-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0004_indexpage_footer_x_link_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='abouts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_titleb', models.CharField(max_length=200)),
                ('about_imageb', models.ImageField(upload_to='media/img/')),
                ('about_descriptionb', models.TextField()),
            ],
        ),
    ]
