# Generated by Django 5.0.2 on 2024-04-25 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cor', '0005_abouts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abouts',
            name='about_imageb',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='about_image',
            field=models.ImageField(upload_to='media'),
        ),
        migrations.AlterField(
            model_name='indexpage',
            name='index_image',
            field=models.ImageField(upload_to='media'),
        ),
    ]
